name: quickfix
description: A platform to order for a technician service and get it done immediately.

version: 1.3.3+9

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  firebase_core: ^0.5.0
  introduction_screen: ^1.0.9
  dartz: ^0.9.1
  shared_preferences: ^0.5.10
  font_awesome_flutter: ^8.8.1
  carousel_slider: ^2.2.1
  http: ^0.12.2
  flushbar: ^1.10.4
  provider: ^4.3.2+2
  connectivity: ^0.4.9+2
  google_maps_flutter: null
  sliding_up_panel: ^1.0.2
  location: ^3.0.2
  flutter_polyline_points: ^0.2.3
  flutter_shimmer: ^1.3.0
  firebase_messaging: ^7.0.0
  badges: ^1.1.1
  image_picker: ^0.6.7+7
  dio: ^3.0.10
  flutter_sparkline: ^0.1.0
  flutter_staggered_grid_view: ^0.3.2
  device_info: ">=0.4.2+4 <2.0.0"
  firebase_auth: null
  cloud_firestore: ^0.14.0+2
  intl: ^0.16.1
  flutter_local_notifications: ^1.4.4+4
  flutter_app_badger: ^1.1.2
  flutter_widgets: ^0.1.12
  photo_view: ^0.10.2
  flutter_statusbarcolor: ^0.2.3
  logger: ^0.9.2
  flutter_svg: ^0.19.0
  rxdart: ^0.24.1
  stacked: ^1.7.6
  url_launcher: ^5.5.0
  package_info: ^0.4.3
  firebase_remote_config: ^0.4.0
  searchable_dropdown: ^1.1.3
  local_auth: ^0.6.3+1
  flutter_lock_screen: "^1.0.5"
  pin_code_fields: ^5.1.0
  flutter_custom_clippers: ^1.1.2
  flutter_staggered_animations: ^0.1.2
  sentry: ">=3.0.0 <4.0.0"
  flutter_dotenv: ^2.1.0
  share: ^0.6.5
  timeago: ^2.0.27
  google_fonts: ^1.1.0
  dots_indicator: ^1.2.0
  geolocation: ^1.1.2
  smartlook:

dev_dependencies:
  flutter_native_splash: ^0.1.9
  flutter_launcher_icons: ^0.8.0
  flutter_test:
    sdk: flutter

flutter_native_splash:
  image: assets/splash2.png
  color: "ffffff"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.jpg"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - .env
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
fonts:
  - family: Sans
    fonts:
      - asset: assets/font/OpenSans-Bold.ttf
        weight: 800
      - asset: assets/font/OpenSans-Semibold.ttf
        weight: 600
      - asset: assets/font/OpenSans-Regular.ttf
        weight: 400
      - asset: assets/font/OpenSans-Light.ttf
        weight: 200
  - family: Popins
    fonts:
      - asset: assets/font/Poppins-Regular.ttf
      - asset: assets/font/Poppins-SemiBold.ttf
        weight: 600
  - family: Pragmatica
    fonts:
      - asset: assets/font/pragmatica_bold.ttf
        weight: 500

