name: quickfix
description: A platform to order for a technician service and get it done immediately.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 5.0+50

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  introduction_screen: ^1.0.8
  shared_preferences: ^0.5.6+2
  font_awesome_flutter: ^8.7.0
  carousel_slider: ^1.4.1
  http: ^0.12.0+4
  flutter_statusbarcolor: ^0.2.3
  provider: ^4.0.4
  connectivity: ^0.4.8+1
  google_maps_flutter:
  sliding_up_panel: ^1.0.2
  location: ^3.0.0
  flutter_shimmer: ^1.2.0
  badges: ^1.1.1
  image_picker: ^0.6.5+3
  dio: ^3.0.9
  firebase_auth:
  responsive_container:


dev_dependencies:
  flutter_native_splash: ^0.1.9
  flutter_launcher_icons: ^0.7.3
  flutter_test:
    sdk: flutter
      
flutter_native_splash:
  image: assets/logo-splash.jpg
  color: "ffffff"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon-logo.png"


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo.png
    - assets/cat.png
    - assets/cc.png
    - assets/dp.png
    - assets/on1.png
    - assets/on2.png
    - assets/on3.png
    - assets/food1.jpeg
    - assets/food2.jpeg
    - assets/food3.jpeg
    - assets/food4.jpeg
    - assets/food5.jpeg
    - assets/food6.jpeg
    - assets/food7.jpeg
    - assets/food8.jpeg
    - assets/food9.jpeg
    - assets/food10.jpeg
    - assets/food11.jpeg
    - assets/food12.jpg
    - assets/cm1.jpeg
    - assets/cm2.jpeg
    - assets/cm3.jpeg
    - assets/cm4.jpeg
    - assets/cm4.jpeg
    - assets/splashscreen.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

fonts:
    - family: Sans
      fonts:
        - asset: assets/font/OpenSans-Bold.ttf
          weight: 800
        - asset: assets/font/OpenSans-Semibold.ttf
          weight: 600
        - asset: assets/font/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/font/OpenSans-Light.ttf
          weight: 200
    - family : Popins
      fonts:
        - asset: assets/font/Poppins-Regular.ttf
        - asset: assets/font/Poppins-SemiBold.ttf
          weight : 600
    - family : Pragmatica
      fonts:
        - asset: assets/font/pragmatica_bold.ttf
          weight: 500

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
