#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/macbook/Library/Android/flutter"
export "FLUTTER_APPLICATION_PATH=/Users/macbook/Documents/Dev/Flutter/fixme"
export "FLUTTER_TARGET=/Users/macbook/Documents/Dev/Flutter/fixme/lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "SYMROOT=${SOURCE_ROOT}/../build/ios"
export "OTHER_LDFLAGS=$(inherited) -framework Flutter"
export "FLUTTER_FRAMEWORK_DIR=/Users/macbook/Library/Android/flutter/bin/cache/artifacts/engine/ios"
export "FLUTTER_BUILD_NAME=1.3.3"
export "FLUTTER_BUILD_NUMBER=9"
export "DART_DEFINES=flutter.inspector.structuredErrors%3Dtrue"
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=.packages"
